### PR TITLE
Proposal for singalong.js talk for December or January

### PR DESCRIPTION
**Pull request by karaokeresearch**
Ross Brackett here. Bret asked me to submit a pull request for a talk proposal for the December or January meetup Here it is! Thanks.

### CODE REVIEW

**Comment by bcomnes** [comment]
Looks awesome!  @maxogden, would this work for waffle.js instead/too?  @karaokeresearch sill on for this thursday Dec 3?

**Comment by karaokeresearch** [comment]
I'm ready to present this week if you folks would like me to.

**Comment by bcomnesjlr** [comment]
@karaokeresearch Cool!  Just got the room confirmed.  We're on! Updating meetup.com, calagator and IRC by end of day.

**Comment by bcomnes** [comment]
@karaokeresearch Cool! Just got the room confirmed. We're on! Updating meetup.com, calagator and IRC by end of day.

**Comment by karaokeresearch** [comment]
Fantastic. I'll get everything ready for Thursday then.

**Comment by bcomnes** [comment]
Posted to calagator and IRC http://calagator.org/events/1250469448

**Comment by bcomnes** [comment]
Re waffle.js which has a musical twist:

> ogd> bret: im having a planning meeting for wafflejs tomorrow with my coorganizer, but we prob wont have the first one till january at least

**Pull request merged**
