### PR TITLE
style: rework layout for better landing page

### PR DESCRIPTION
**Pull request by ungoldman**
## before

screen shot 2017-09-02 at 12 32 42 am

## now

pdxnode org-

### CODE REVIEW

**Comment by ungoldman** [comment]
Hey @obensource, just noticed you didn't add our new organizers to the github group.

Do you know their handles? I'd like to add them as reviewers on here from time to time.

**Comment by obensource** [comment]
@ungoldman AWESOME! 🙌

My bad. Just invited everyone as members: @boneskull @michellejl @ottoetc @abstractmachines @jinglish

**Comment by ungoldman** [comment]
Deployed! http://pdxnode.org/

**Comment by obensource** [comment]
@ungoldman wahoo! 🙌

**Comment by jinglish** [comment]
Looks DOPE

**Comment by boneskull** [comment]
wicked innit

**Comment by bcomnes** [comment]
Looks good

**Pull request merged**
